!!com.compuware.ispw.wzzms.models.IspwRoot
ispwApplication:
  host: cwcc.bmc.com
  port: 16196
  runtimeConfig: iccga
  stream: GITDEMO1
  application: GITI
  assignmentPrefix: GITI
  sandbox: Y
  pathMappings:
  - path: "**/Sources/CommonComponents/Progs"
    types:
    - fileExtension: cbl
      ispwType: COB
    - fileExtension: pli
      ispwType: PLI
  - path: "**/Sources/CommonComponents/Subs"
    types:
    - fileExtension: cbl
      ispwType: COB
    - fileExtension: pli
      ispwType: PLI
  - path: "**/Sources/CommonComponents/Jobs"
    types:
    - fileExtension: jcl
      ispwType: JOB                        
  - path: "**/Sources/CommonComponents/Copys"
    types:
    - fileExtension: cpy
      ispwType: COPY
    - fileExtension: incl
      ispwType: INCL